# docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:4.0 jekyll serve

version: '3'
services:
  jekyll-serve:
    #image: jekyll/jekyll:4.0
    image: bretfisher/jekyll-serve
    volumes:
      #- '.:/srv/jekyll'
      - '.:/site'
    ports:
      - 4000:4000
    # command: 'jekyll serve'